assets: /lumos-vePFS/suzhou/Users/ruan/PIVOT-Q/third_party/LIBERO/libero/libero/assets
bddl_files: /lumos-vePFS/suzhou/Users/ruan/PIVOT-Q/third_party/LIBERO/libero/libero/bddl_files
benchmark_root: /lumos-vePFS/suzhou/Users/ruan/PIVOT-Q/third_party/LIBERO/libero/libero
datasets: /lumos-vePFS/suzhou/Users/ruan/PIVOT-Q/third_party/LIBERO/datasets
init_states: /lumos-vePFS/suzhou/Users/ruan/PIVOT-Q/third_party/LIBERO/libero/libero/init_files
